version: "3.9"

services:
  app:
    build: .
    container_name: casso-app
    ports:
      - "8501:8501"
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
